name: Docker Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t logger .
    
    - name: Test Docker image
      run: |
        mkdir -p logs
        docker run -d -v "$(pwd)/logs/:/home/logs/" logger
        sleep 5
        cat logs/log.txt
